 SELECT 'radiology_prompts' as table_name, count(*) as record_count FROM radiology_prompts
 SELECT 'dicom_routing_rules' as table_name, count(*) as record_count FROM dicom_routing_rules
 SELECT 'radiology_scheduled_procedures' as table_name, count(*) as record_count FROM radiology_scheduled_procedures
 SELECT 'ai_provider_settings' as table_name, count(*) as record_count FROM ai_provider_settings
 SELECT 'ai_reporting_audit_logs' as table_name, count(*) as record_count FROM ai_reporting_audit_logs
 SELECT 'ai_reporting_drafts' as table_name, count(*) as record_count FROM ai_reporting_drafts
 SELECT 'radiology_image_references' as table_name, count(*) as record_count FROM radiology_image_references
 SELECT 'radiology_worklist' as table_name, count(*) as record_count FROM radiology_worklist
 SELECT 'radiology_audit_log' as table_name, count(*) as record_count FROM radiology_audit_log
 SELECT 'pacs_settings' as table_name, count(*) as record_count FROM pacs_settings
 SELECT 'dicom_pull_jobs' as table_name, count(*) as record_count FROM dicom_pull_jobs
 SELECT 'pacs_logs' as table_name, count(*) as record_count FROM pacs_logs
 SELECT 'radiology_studies' as table_name, count(*) as record_count FROM radiology_studies
 SELECT 'radiology_report_drafts' as table_name, count(*) as record_count FROM radiology_report_drafts
 SELECT 'radiology_voice_logs' as table_name, count(*) as record_count FROM radiology_voice_logs
 SELECT 'radiology_report_key_images' as table_name, count(*) as record_count FROM radiology_report_key_images
 SELECT 'radiology_priority_rules' as table_name, count(*) as record_count FROM radiology_priority_rules
 SELECT 'radiology_critical_findings' as table_name, count(*) as record_count FROM radiology_critical_findings
 SELECT 'radiology_report_verifications' as table_name, count(*) as record_count FROM radiology_report_verifications
 SELECT 'radiology_tat_tracking' as table_name, count(*) as record_count FROM radiology_tat_tracking
 SELECT 'radiology_structured_templates' as table_name, count(*) as record_count FROM radiology_structured_templates
 SELECT 'radiology_ai_enhancements' as table_name, count(*) as record_count FROM radiology_ai_enhancements
 SELECT 'radiology_dicom_measurements' as table_name, count(*) as record_count FROM radiology_dicom_measurements
 SELECT 'radiology_multi_site_worklist' as table_name, count(*) as record_count FROM radiology_multi_site_worklist
 SELECT 'teleradiology_sites' as table_name, count(*) as record_count FROM teleradiology_sites
 SELECT 'dicom_routing_optimization_log' as table_name, count(*) as record_count FROM dicom_routing_optimization_log
 SELECT 'dicom_pull_agent_logs' as table_name, count(*) as record_count FROM dicom_pull_agent_logs
 SELECT 'dicom_pull_agent_status' as table_name, count(*) as record_count FROM dicom_pull_agent_status
 SELECT 'radiology_text_macros' as table_name, count(*) as record_count FROM radiology_text_macros
 SELECT 'radiology_report_preferences' as table_name, count(*) as record_count FROM radiology_report_preferences
 SELECT 'dicom_modalities' as table_name, count(*) as record_count FROM dicom_modalities
 SELECT 'radiology_film_issues' as table_name, count(*) as record_count FROM radiology_film_issues
 SELECT 'radiology_share_links' as table_name, count(*) as record_count FROM radiology_share_links
 SELECT 'report_shares' as table_name, count(*) as record_count FROM report_shares
 SELECT 'report_templates' as table_name, count(*) as record_count FROM report_templates
 SELECT 'dicom_pulled_studies' as table_name, count(*) as record_count FROM dicom_pulled_studies
 SELECT 'dicom_failed_retrieval_queue' as table_name, count(*) as record_count FROM dicom_failed_retrieval_queue
 SELECT 'radiology_normal_snippets' as table_name, count(*) as record_count FROM radiology_normal_snippets
 SELECT 'radiology_report_lifecycle_log' as table_name, count(*) as record_count FROM radiology_report_lifecycle_log
 SELECT 'ai_server_health_log' as table_name, count(*) as record_count FROM ai_server_health_log
 SELECT 'pacs_archive_lifecycle' as table_name, count(*) as record_count FROM pacs_archive_lifecycle
 SELECT 'ai_impressions' as table_name, count(*) as record_count FROM ai_impressions
 SELECT 'dicom_sr_export_queue' as table_name, count(*) as record_count FROM dicom_sr_export_queue
 SELECT 'report_amendments' as table_name, count(*) as record_count FROM report_amendments
 SELECT 'report_quality_checks' as table_name, count(*) as record_count FROM report_quality_checks
 SELECT 'report_translations' as table_name, count(*) as record_count FROM report_translations
 SELECT 'study_tat_metrics' as table_name, count(*) as record_count FROM study_tat_metrics
 SELECT 'template_learning' as table_name, count(*) as record_count FROM template_learning
 SELECT 'dicom_retry_queue' as table_name, count(*) as record_count FROM dicom_retry_queue
 SELECT 'report_delivery_tracking' as table_name, count(*) as record_count FROM report_delivery_tracking
 SELECT 'dicom_nodes' as table_name, count(*) as record_count FROM dicom_nodes
 SELECT 'ai_prompt_templates' as table_name, count(*) as record_count FROM ai_prompt_templates
 SELECT 'ai_model_routes' as table_name, count(*) as record_count FROM ai_model_routes
 SELECT 'ai_quality_scores' as table_name, count(*) as record_count FROM ai_quality_scores
 SELECT 'ai_dicom_findings' as table_name, count(*) as record_count FROM ai_dicom_findings
 SELECT 'report_template_versions' as table_name, count(*) as record_count FROM report_template_versions
 SELECT 'ai_billing_suggestions' as table_name, count(*) as record_count FROM ai_billing_suggestions
 SELECT 'ai_training_data_exports' as table_name, count(*) as record_count FROM ai_training_data_exports
 SELECT 'report_quality_gates' as table_name, count(*) as record_count FROM report_quality_gates
 SELECT 'ai_provider_health_logs' as table_name, count(*) as record_count FROM ai_provider_health_logs
 SELECT 'ai_voice_transcriptions' as table_name, count(*) as record_count FROM ai_voice_transcriptions
 SELECT 'ai_patient_communications' as table_name, count(*) as record_count FROM ai_patient_communications
 SELECT 'ai_normal_report_templates' as table_name, count(*) as record_count FROM ai_normal_report_templates
 SELECT 'radiology_smart_macros' as table_name, count(*) as record_count FROM radiology_smart_macros
 SELECT 'dicom_studies' as table_name, count(*) as record_count FROM dicom_studies
 SELECT 'report_delivery_logs' as table_name, count(*) as record_count FROM report_delivery_logs
 SELECT 'radiology_snippets' as table_name, count(*) as record_count FROM radiology_snippets
 SELECT 'radiology_master_templates' as table_name, count(*) as record_count FROM radiology_master_templates
 SELECT 'radiology_template_versions' as table_name, count(*) as record_count FROM radiology_template_versions
 SELECT 'radiology_personal_templates' as table_name, count(*) as record_count FROM radiology_personal_templates
 SELECT 'radiology_template_packs' as table_name, count(*) as record_count FROM radiology_template_packs
 SELECT 'radiology_knowledge_base' as table_name, count(*) as record_count FROM radiology_knowledge_base
 SELECT 'radiology_template_usage' as table_name, count(*) as record_count FROM radiology_template_usage
 SELECT 'radiology_template_favorites' as table_name, count(*) as record_count FROM radiology_template_favorites
 SELECT 'radiology_template_comparison' as table_name, count(*) as record_count FROM radiology_template_comparison
 SELECT 'ai_prompt_library_versions' as table_name, count(*) as record_count FROM ai_prompt_library_versions
 SELECT 'ai_prompt_library' as table_name, count(*) as record_count FROM ai_prompt_library
 SELECT 'teaching_cases' as table_name, count(*) as record_count FROM teaching_cases
 SELECT 'teaching_case_images' as table_name, count(*) as record_count FROM teaching_case_images
 SELECT 'teaching_case_collections' as table_name, count(*) as record_count FROM teaching_case_collections
 SELECT 'teaching_case_favorites' as table_name, count(*) as record_count FROM teaching_case_favorites
 SELECT 'teaching_case_views' as table_name, count(*) as record_count FROM teaching_case_views
 SELECT 'teaching_case_notes' as table_name, count(*) as record_count FROM teaching_case_notes
 SELECT 'measurement_history' as table_name, count(*) as record_count FROM measurement_history
 SELECT 'radiology_memory' as table_name, count(*) as record_count FROM radiology_memory
 SELECT 'radiology_memory_patterns' as table_name, count(*) as record_count FROM radiology_memory_patterns
 SELECT 'radiology_memory_measurements' as table_name, count(*) as record_count FROM radiology_memory_measurements
 SELECT 'radiology_memory_classifications' as table_name, count(*) as record_count FROM radiology_memory_classifications
 SELECT 'radiology_memory_phrases' as table_name, count(*) as record_count FROM radiology_memory_phrases
 SELECT 'radiology_memory_impressions' as table_name, count(*) as record_count FROM radiology_memory_impressions
 SELECT 'radiology_memory_decisions' as table_name, count(*) as record_count FROM radiology_memory_decisions
 SELECT 'radiology_memory_feedback' as table_name, count(*) as record_count FROM radiology_memory_feedback
 SELECT 'radiology_memory_usage' as table_name, count(*) as record_count FROM radiology_memory_usage
 SELECT 'radiology_lesions' as table_name, count(*) as record_count FROM radiology_lesions
 SELECT 'radiology_lesion_timeline' as table_name, count(*) as record_count FROM radiology_lesion_timeline
 SELECT 'radiology_measurements' as table_name, count(*) as record_count FROM radiology_measurements
 SELECT 'radiology_spine_sessions' as table_name, count(*) as record_count FROM radiology_spine_sessions
 SELECT 'radiology_spine_levels' as table_name, count(*) as record_count FROM radiology_spine_levels
 SELECT 'radiology_brain_sessions' as table_name, count(*) as record_count FROM radiology_brain_sessions
 SELECT 'radiology_tumor_followups' as table_name, count(*) as record_count FROM radiology_tumor_followups
 SELECT 'radiology_annotations' as table_name, count(*) as record_count FROM radiology_annotations
 SELECT 'radiology_ai_review_audits' as table_name, count(*) as record_count FROM radiology_ai_review_audits
 SELECT 'teleradiology_users' as table_name, count(*) as record_count FROM teleradiology_users
 SELECT 'teleradiology_sessions' as table_name, count(*) as record_count FROM teleradiology_sessions
 SELECT 'teleradiology_assignments' as table_name, count(*) as record_count FROM teleradiology_assignments
 SELECT 'ai_extraction_results' as table_name, count(*) as record_count FROM ai_extraction_results
 SELECT 'ai_job_queue' as table_name, count(*) as record_count FROM ai_job_queue
 SELECT 'dicom_incoming_studies' as table_name, count(*) as record_count FROM dicom_incoming_studies
 SELECT 'dicom_study_audit_log' as table_name, count(*) as record_count FROM dicom_study_audit_log
 SELECT 'dicom_study_series' as table_name, count(*) as record_count FROM dicom_study_series
 SELECT 'pacs_storage_tier' as table_name, count(*) as record_count FROM pacs_storage_tier
 SELECT 'radiology_impression_rules' as table_name, count(*) as record_count FROM radiology_impression_rules
 SELECT 'radiology_smart_findings' as table_name, count(*) as record_count FROM radiology_smart_findings
 SELECT 'radiology_smart_usage' as table_name, count(*) as record_count FROM radiology_smart_usage
 SELECT 'study_access_log' as table_name, count(*) as record_count FROM study_access_log
 SELECT 'radiology_favorite_finding_sets' as table_name, count(*) as record_count FROM radiology_favorite_finding_sets
 SELECT 'radiology_smart_findings_audit' as table_name, count(*) as record_count FROM radiology_smart_findings_audit

