 SELECT 'radiology_prompts' as table_name, count(*) as record_count FROM radiology_prompts UNION ALL 
 SELECT 'dicom_routing_rules' as table_name, count(*) as record_count FROM dicom_routing_rules UNION ALL 
 SELECT 'radiology_scheduled_procedures' as table_name, count(*) as record_count FROM radiology_scheduled_procedures UNION ALL 
 SELECT 'ai_provider_settings' as table_name, count(*) as record_count FROM ai_provider_settings UNION ALL 
 SELECT 'ai_reporting_audit_logs' as table_name, count(*) as record_count FROM ai_reporting_audit_logs UNION ALL 
 SELECT 'ai_reporting_drafts' as table_name, count(*) as record_count FROM ai_reporting_drafts UNION ALL 
 SELECT 'radiology_image_references' as table_name, count(*) as record_count FROM radiology_image_references UNION ALL 
 SELECT 'radiology_worklist' as table_name, count(*) as record_count FROM radiology_worklist UNION ALL 
 SELECT 'radiology_audit_log' as table_name, count(*) as record_count FROM radiology_audit_log UNION ALL 
 SELECT 'pacs_settings' as table_name, count(*) as record_count FROM pacs_settings UNION ALL 
 SELECT 'dicom_pull_jobs' as table_name, count(*) as record_count FROM dicom_pull_jobs UNION ALL 
 SELECT 'pacs_logs' as table_name, count(*) as record_count FROM pacs_logs UNION ALL 
 SELECT 'radiology_studies' as table_name, count(*) as record_count FROM radiology_studies UNION ALL 
 SELECT 'radiology_report_drafts' as table_name, count(*) as record_count FROM radiology_report_drafts UNION ALL 
 SELECT 'radiology_voice_logs' as table_name, count(*) as record_count FROM radiology_voice_logs UNION ALL 
 SELECT 'radiology_report_key_images' as table_name, count(*) as record_count FROM radiology_report_key_images UNION ALL 
 SELECT 'radiology_priority_rules' as table_name, count(*) as record_count FROM radiology_priority_rules UNION ALL 
 SELECT 'radiology_critical_findings' as table_name, count(*) as record_count FROM radiology_critical_findings UNION ALL 
 SELECT 'radiology_report_verifications' as table_name, count(*) as record_count FROM radiology_report_verifications UNION ALL 
 SELECT 'radiology_tat_tracking' as table_name, count(*) as record_count FROM radiology_tat_tracking UNION ALL 
 SELECT 'radiology_structured_templates' as table_name, count(*) as record_count FROM radiology_structured_templates UNION ALL 
 SELECT 'radiology_ai_enhancements' as table_name, count(*) as record_count FROM radiology_ai_enhancements UNION ALL 
 SELECT 'radiology_dicom_measurements' as table_name, count(*) as record_count FROM radiology_dicom_measurements UNION ALL 
 SELECT 'radiology_multi_site_worklist' as table_name, count(*) as record_count FROM radiology_multi_site_worklist UNION ALL 
 SELECT 'teleradiology_sites' as table_name, count(*) as record_count FROM teleradiology_sites UNION ALL 
 SELECT 'dicom_routing_optimization_log' as table_name, count(*) as record_count FROM dicom_routing_optimization_log UNION ALL 
 SELECT 'dicom_pull_agent_logs' as table_name, count(*) as record_count FROM dicom_pull_agent_logs UNION ALL 
 SELECT 'dicom_pull_agent_status' as table_name, count(*) as record_count FROM dicom_pull_agent_status UNION ALL 
 SELECT 'radiology_text_macros' as table_name, count(*) as record_count FROM radiology_text_macros UNION ALL 
 SELECT 'radiology_report_preferences' as table_name, count(*) as record_count FROM radiology_report_preferences UNION ALL 
 SELECT 'dicom_modalities' as table_name, count(*) as record_count FROM dicom_modalities UNION ALL 
 SELECT 'radiology_film_issues' as table_name, count(*) as record_count FROM radiology_film_issues UNION ALL 
 SELECT 'radiology_share_links' as table_name, count(*) as record_count FROM radiology_share_links UNION ALL 
 SELECT 'report_shares' as table_name, count(*) as record_count FROM report_shares UNION ALL 
 SELECT 'report_templates' as table_name, count(*) as record_count FROM report_templates UNION ALL 
 SELECT 'dicom_pulled_studies' as table_name, count(*) as record_count FROM dicom_pulled_studies UNION ALL 
 SELECT 'dicom_failed_retrieval_queue' as table_name, count(*) as record_count FROM dicom_failed_retrieval_queue UNION ALL 
 SELECT 'radiology_normal_snippets' as table_name, count(*) as record_count FROM radiology_normal_snippets UNION ALL 
 SELECT 'radiology_report_lifecycle_log' as table_name, count(*) as record_count FROM radiology_report_lifecycle_log UNION ALL 
 SELECT 'ai_server_health_log' as table_name, count(*) as record_count FROM ai_server_health_log UNION ALL 
 SELECT 'pacs_archive_lifecycle' as table_name, count(*) as record_count FROM pacs_archive_lifecycle UNION ALL 
 SELECT 'ai_impressions' as table_name, count(*) as record_count FROM ai_impressions UNION ALL 
 SELECT 'dicom_sr_export_queue' as table_name, count(*) as record_count FROM dicom_sr_export_queue UNION ALL 
 SELECT 'report_amendments' as table_name, count(*) as record_count FROM report_amendments UNION ALL 
 SELECT 'report_quality_checks' as table_name, count(*) as record_count FROM report_quality_checks UNION ALL 
 SELECT 'report_translations' as table_name, count(*) as record_count FROM report_translations UNION ALL 
 SELECT 'study_tat_metrics' as table_name, count(*) as record_count FROM study_tat_metrics UNION ALL 
 SELECT 'template_learning' as table_name, count(*) as record_count FROM template_learning UNION ALL 
 SELECT 'dicom_retry_queue' as table_name, count(*) as record_count FROM dicom_retry_queue UNION ALL 
 SELECT 'report_delivery_tracking' as table_name, count(*) as record_count FROM report_delivery_tracking UNION ALL 
 SELECT 'dicom_nodes' as table_name, count(*) as record_count FROM dicom_nodes UNION ALL 
 SELECT 'ai_prompt_templates' as table_name, count(*) as record_count FROM ai_prompt_templates UNION ALL 
 SELECT 'ai_model_routes' as table_name, count(*) as record_count FROM ai_model_routes UNION ALL 
 SELECT 'ai_quality_scores' as table_name, count(*) as record_count FROM ai_quality_scores UNION ALL 
 SELECT 'ai_dicom_findings' as table_name, count(*) as record_count FROM ai_dicom_findings UNION ALL 
 SELECT 'report_template_versions' as table_name, count(*) as record_count FROM report_template_versions UNION ALL 
 SELECT 'ai_billing_suggestions' as table_name, count(*) as record_count FROM ai_billing_suggestions UNION ALL 
 SELECT 'ai_training_data_exports' as table_name, count(*) as record_count FROM ai_training_data_exports UNION ALL 
 SELECT 'report_quality_gates' as table_name, count(*) as record_count FROM report_quality_gates UNION ALL 
 SELECT 'ai_provider_health_logs' as table_name, count(*) as record_count FROM ai_provider_health_logs UNION ALL 
 SELECT 'ai_voice_transcriptions' as table_name, count(*) as record_count FROM ai_voice_transcriptions UNION ALL 
 SELECT 'ai_patient_communications' as table_name, count(*) as record_count FROM ai_patient_communications UNION ALL 
 SELECT 'ai_normal_report_templates' as table_name, count(*) as record_count FROM ai_normal_report_templates UNION ALL 
 SELECT 'radiology_smart_macros' as table_name, count(*) as record_count FROM radiology_smart_macros UNION ALL 
 SELECT 'dicom_studies' as table_name, count(*) as record_count FROM dicom_studies UNION ALL 
 SELECT 'report_delivery_logs' as table_name, count(*) as record_count FROM report_delivery_logs UNION ALL 
 SELECT 'radiology_snippets' as table_name, count(*) as record_count FROM radiology_snippets UNION ALL 
 SELECT 'radiology_master_templates' as table_name, count(*) as record_count FROM radiology_master_templates UNION ALL 
 SELECT 'radiology_template_versions' as table_name, count(*) as record_count FROM radiology_template_versions UNION ALL 
 SELECT 'radiology_personal_templates' as table_name, count(*) as record_count FROM radiology_personal_templates UNION ALL 
 SELECT 'radiology_template_packs' as table_name, count(*) as record_count FROM radiology_template_packs UNION ALL 
 SELECT 'radiology_knowledge_base' as table_name, count(*) as record_count FROM radiology_knowledge_base UNION ALL 
 SELECT 'radiology_template_usage' as table_name, count(*) as record_count FROM radiology_template_usage UNION ALL 
 SELECT 'radiology_template_favorites' as table_name, count(*) as record_count FROM radiology_template_favorites UNION ALL 
 SELECT 'radiology_template_comparison' as table_name, count(*) as record_count FROM radiology_template_comparison UNION ALL 
 SELECT 'ai_prompt_library_versions' as table_name, count(*) as record_count FROM ai_prompt_library_versions UNION ALL 
 SELECT 'ai_prompt_library' as table_name, count(*) as record_count FROM ai_prompt_library UNION ALL 
 SELECT 'teaching_cases' as table_name, count(*) as record_count FROM teaching_cases UNION ALL 
 SELECT 'teaching_case_images' as table_name, count(*) as record_count FROM teaching_case_images UNION ALL 
 SELECT 'teaching_case_collections' as table_name, count(*) as record_count FROM teaching_case_collections UNION ALL 
 SELECT 'teaching_case_favorites' as table_name, count(*) as record_count FROM teaching_case_favorites UNION ALL 
 SELECT 'teaching_case_views' as table_name, count(*) as record_count FROM teaching_case_views UNION ALL 
 SELECT 'teaching_case_notes' as table_name, count(*) as record_count FROM teaching_case_notes UNION ALL 
 SELECT 'measurement_history' as table_name, count(*) as record_count FROM measurement_history UNION ALL 
 SELECT 'radiology_memory' as table_name, count(*) as record_count FROM radiology_memory UNION ALL 
 SELECT 'radiology_memory_patterns' as table_name, count(*) as record_count FROM radiology_memory_patterns UNION ALL 
 SELECT 'radiology_memory_measurements' as table_name, count(*) as record_count FROM radiology_memory_measurements UNION ALL 
 SELECT 'radiology_memory_classifications' as table_name, count(*) as record_count FROM radiology_memory_classifications UNION ALL 
 SELECT 'radiology_memory_phrases' as table_name, count(*) as record_count FROM radiology_memory_phrases UNION ALL 
 SELECT 'radiology_memory_impressions' as table_name, count(*) as record_count FROM radiology_memory_impressions UNION ALL 
 SELECT 'radiology_memory_decisions' as table_name, count(*) as record_count FROM radiology_memory_decisions UNION ALL 
 SELECT 'radiology_memory_feedback' as table_name, count(*) as record_count FROM radiology_memory_feedback UNION ALL 
 SELECT 'radiology_memory_usage' as table_name, count(*) as record_count FROM radiology_memory_usage UNION ALL 
 SELECT 'radiology_lesions' as table_name, count(*) as record_count FROM radiology_lesions UNION ALL 
 SELECT 'radiology_lesion_timeline' as table_name, count(*) as record_count FROM radiology_lesion_timeline UNION ALL 
 SELECT 'radiology_measurements' as table_name, count(*) as record_count FROM radiology_measurements UNION ALL 
 SELECT 'radiology_spine_sessions' as table_name, count(*) as record_count FROM radiology_spine_sessions UNION ALL 
 SELECT 'radiology_spine_levels' as table_name, count(*) as record_count FROM radiology_spine_levels UNION ALL 
 SELECT 'radiology_brain_sessions' as table_name, count(*) as record_count FROM radiology_brain_sessions UNION ALL 
 SELECT 'radiology_tumor_followups' as table_name, count(*) as record_count FROM radiology_tumor_followups UNION ALL 
 SELECT 'radiology_annotations' as table_name, count(*) as record_count FROM radiology_annotations UNION ALL 
 SELECT 'radiology_ai_review_audits' as table_name, count(*) as record_count FROM radiology_ai_review_audits UNION ALL 
 SELECT 'teleradiology_users' as table_name, count(*) as record_count FROM teleradiology_users UNION ALL 
 SELECT 'teleradiology_sessions' as table_name, count(*) as record_count FROM teleradiology_sessions UNION ALL 
 SELECT 'teleradiology_assignments' as table_name, count(*) as record_count FROM teleradiology_assignments UNION ALL 
 SELECT 'ai_extraction_results' as table_name, count(*) as record_count FROM ai_extraction_results UNION ALL 
 SELECT 'ai_job_queue' as table_name, count(*) as record_count FROM ai_job_queue UNION ALL 
 SELECT 'dicom_incoming_studies' as table_name, count(*) as record_count FROM dicom_incoming_studies UNION ALL 
 SELECT 'dicom_study_audit_log' as table_name, count(*) as record_count FROM dicom_study_audit_log UNION ALL 
 SELECT 'dicom_study_series' as table_name, count(*) as record_count FROM dicom_study_series UNION ALL 
 SELECT 'pacs_storage_tier' as table_name, count(*) as record_count FROM pacs_storage_tier UNION ALL 
 SELECT 'radiology_impression_rules' as table_name, count(*) as record_count FROM radiology_impression_rules UNION ALL 
 SELECT 'radiology_smart_findings' as table_name, count(*) as record_count FROM radiology_smart_findings UNION ALL 
 SELECT 'radiology_smart_usage' as table_name, count(*) as record_count FROM radiology_smart_usage UNION ALL 
 SELECT 'study_access_log' as table_name, count(*) as record_count FROM study_access_log UNION ALL 
 SELECT 'radiology_favorite_finding_sets' as table_name, count(*) as record_count FROM radiology_favorite_finding_sets UNION ALL 
 SELECT 'radiology_smart_findings_audit' as table_name, count(*) as record_count FROM radiology_smart_findings_audit UNION ALL 

