import { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogClose,
} from "@/components/ui/dialog";
import {
  Printer, FileText, FileSpreadsheet, FileType, Mail, Loader2,
  CheckCircle2, AlertCircle,
} from "lucide-react";

// ─── Public types (consumed by pages) ────────────────────────────────────────

export type ExportSection = {
  title: string;
  /** Array of [label, formatted-value] pairs */
  metrics: [string, string][];
};

export type ExportTable = {
  title: string;
  headers: string[];
  rows: (string | number)[][];
};

export type ExportConfig = {
  /** Appears as document title and email subject prefix */
  title: string;
  /** Date range or single date string */
  subtitle: string;
  sections: ExportSection[];
  tables: ExportTable[];
};

// ─── Shared HTML builder (Print / Word / Email) ───────────────────────────────

function buildHTML(config: ExportConfig): string {
  const sectionHTML = config.sections
    .map(
      (s) => `
    <h2 style="font-size:13px;color:#1e40af;border-bottom:2px solid #e5e7eb;padding-bottom:4px;margin:18px 0 6px">${s.title}</h2>
    <table style="width:100%;border-collapse:collapse;margin-bottom:6px">
      ${s.metrics
        .map(
          ([label, value], i) => `
        <tr style="background:${i % 2 === 0 ? "#f8fafc" : "white"}">
          <td style="padding:5px 10px;font-size:11px;color:#6b7280;width:55%">${label}</td>
          <td style="padding:5px 10px;font-size:11px;font-weight:600;color:#111827">${value}</td>
        </tr>`,
        )
        .join("")}
    </table>`,
    )
    .join("");

  const tableHTML = config.tables
    .map(
      (t) => `
    <h2 style="font-size:13px;color:#1e40af;border-bottom:2px solid #e5e7eb;padding-bottom:4px;margin:18px 0 6px">${t.title}</h2>
    <table style="width:100%;border-collapse:collapse;margin-bottom:6px;font-size:10px">
      <thead>
        <tr>${t.headers
          .map(
            (h) =>
              `<th style="padding:6px 8px;background:#1e40af;color:white;text-align:left;font-size:10px">${h}</th>`,
          )
          .join("")}</tr>
      </thead>
      <tbody>
        ${t.rows
          .map(
            (row, i) => `
          <tr style="background:${i % 2 === 0 ? "#f8fafc" : "white"}">
            ${row
              .map(
                (cell) =>
                  `<td style="padding:4px 8px;border-bottom:1px solid #e5e7eb">${cell}</td>`,
              )
              .join("")}
          </tr>`,
          )
          .join("")}
      </tbody>
    </table>`,
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>${config.title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
           margin: 0; padding: 20px; color: #111827; }
    @media print { body { padding: 0; } @page { margin: 10mm; size: A4 landscape; } }
  </style>
</head>
<body>
  <div style="background:#1e40af;color:white;padding:14px 18px;border-radius:6px 6px 0 0">
    <h1 style="margin:0;font-size:18px;font-weight:700">${config.title}</h1>
    <p style="margin:3px 0 0;opacity:.85;font-size:12px">${config.subtitle}</p>
  </div>
  <div style="background:white;border:1px solid #e2e8f0;border-top:none;
              padding:14px 18px;border-radius:0 0 6px 6px">
    ${sectionHTML}
    ${tableHTML}
    <p style="margin:16px 0 0;font-size:9px;color:#9ca3af;
              border-top:1px solid #e5e7eb;padding-top:8px">
      Generated by DiagnoCenter ERP &bull; ${new Date().toLocaleString("en-IN")}
    </p>
  </div>
</body>
</html>`;
}

// ─── Export implementations ───────────────────────────────────────────────────

function doPrint(config: ExportConfig) {
  const html = buildHTML(config);
  const w = window.open("", "_blank");
  if (!w) { alert("Please allow pop-ups to use Print."); return; }
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 350);
}

async function downloadPDF(config: ExportConfig): Promise<void> {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();

  // Blue header bar
  doc.setFillColor(30, 64, 175);
  doc.rect(0, 0, pageW, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15);
  doc.text(config.title, 12, 12);
  doc.setFontSize(9);
  doc.text(config.subtitle, 12, 19);

  let y = 28;

  // Summary sections
  for (const section of config.sections) {
    if (y > 170) { doc.addPage(); y = 12; }
    doc.setTextColor(30, 64, 175);
    doc.setFontSize(10);
    doc.text(section.title, 12, y);
    y += 1;

    autoTable(doc, {
      startY: y,
      head: [["Metric", "Value"]],
      body: section.metrics,
      theme: "striped",
      styles: { fontSize: 8, cellPadding: 2 },
      headStyles: { fillColor: [30, 64, 175] as [number, number, number], textColor: [255, 255, 255] as [number, number, number], fontSize: 8 },
      columnStyles: { 0: { cellWidth: 85 }, 1: { fontStyle: "bold" } },
      margin: { left: 12, right: 12 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  // Data tables
  for (const table of config.tables) {
    if (y > 160) { doc.addPage(); y = 12; }
    doc.setTextColor(30, 64, 175);
    doc.setFontSize(10);
    doc.text(table.title, 12, y);
    y += 1;

    autoTable(doc, {
      startY: y,
      head: [table.headers],
      body: table.rows.map((row) => row.map(String)),
      theme: "striped",
      styles: { fontSize: 7, cellPadding: 1.5, overflow: "linebreak" },
      headStyles: { fillColor: [30, 64, 175] as [number, number, number], textColor: [255, 255, 255] as [number, number, number], fontSize: 7 },
      margin: { left: 12, right: 12 },
    });
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  // Page footers
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `DiagnoCenter ERP  •  ${new Date().toLocaleString("en-IN")}  •  Page ${i} of ${total}`,
      12,
      doc.internal.pageSize.getHeight() - 5,
    );
  }

  doc.save(sanitizeFilename(config.title) + ".pdf");
}

function downloadExcel(config: ExportConfig) {
  const wb = XLSX.utils.book_new();

  // Summary sheet (all sections)
  const summaryData: (string | number)[][] = [
    [config.title],
    [config.subtitle],
    [`Generated: ${new Date().toLocaleString("en-IN")}`],
    [],
  ];
  for (const section of config.sections) {
    summaryData.push([section.title, ""], ...section.metrics, []);
  }
  const summaryWs = XLSX.utils.aoa_to_sheet(summaryData);
  summaryWs["!cols"] = [{ wch: 48 }, { wch: 22 }];
  XLSX.utils.book_append_sheet(wb, summaryWs, "Summary");

  // One sheet per table
  for (const table of config.tables) {
    const sheetData: (string | number)[][] = [
      [table.title],
      [`${config.subtitle}  •  Generated: ${new Date().toLocaleString("en-IN")}`],
      [],
      table.headers,
      ...table.rows,
    ];
    const ws = XLSX.utils.aoa_to_sheet(sheetData);
    ws["!cols"] = table.headers.map(() => ({ wch: 18 }));
    const name = table.title.substring(0, 31).replace(/[\\/?*[\]:]/g, "_");
    XLSX.utils.book_append_sheet(wb, ws, name);
  }

  XLSX.writeFile(wb, sanitizeFilename(config.title) + ".xlsx");
}

function downloadWord(config: ExportConfig) {
  const html = buildHTML(config);
  const blob = new Blob([html], { type: "application/msword; charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = sanitizeFilename(config.title) + ".doc";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

async function sendSummaryEmail(
  config: ExportConfig,
  to: string,
  endpoint: string,
): Promise<{ ok: boolean; error?: string }> {
  try {
    const res = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify({
        to,
        subject: `${config.title} — ${config.subtitle}`,
        htmlBody: buildHTML(config),
      }),
    });
    if (!res.ok) {
      const body = await res.json().catch(() => ({})) as { error?: string };
      return { ok: false, error: body.error ?? `Server error ${res.status}` };
    }
    return res.json() as Promise<{ ok: boolean; error?: string }>;
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : "Network error" };
  }
}

function sanitizeFilename(s: string) {
  return s.replace(/[^\w\s-]/g, "").replace(/\s+/g, "_").substring(0, 60);
}

// ─── Toolbar Component ────────────────────────────────────────────────────────

export function SummaryExportToolbar({
  config,
  emailEndpoint,
}: {
  config: ExportConfig | null;
  emailEndpoint: string;
}) {
  const [pdfBusy, setPdfBusy] = useState(false);
  const [emailOpen, setEmailOpen] = useState(false);
  const [emailTo, setEmailTo] = useState("");
  const [sending, setSending] = useState(false);
  const [result, setResult] = useState<{ ok: boolean; error?: string } | null>(null);

  if (!config) return null;

  async function handlePDF() {
    setPdfBusy(true);
    try { await downloadPDF(config!); }
    finally { setPdfBusy(false); }
  }

  function openEmail() {
    setEmailTo("");
    setResult(null);
    setEmailOpen(true);
  }

  async function handleSend() {
    const addr = emailTo.trim();
    if (!addr) return;
    setSending(true);
    setResult(null);
    const r = await sendSummaryEmail(config!, addr, emailEndpoint);
    setResult(r);
    setSending(false);
  }

  return (
    <>
      <div className="flex flex-wrap items-center gap-1.5">
        <Button
          variant="outline" size="sm"
          className="h-8 gap-1.5 text-xs"
          onClick={() => doPrint(config)}
        >
          <Printer size={13} /> Print
        </Button>

        <Button
          variant="outline" size="sm"
          className="h-8 gap-1.5 text-xs"
          onClick={handlePDF}
          disabled={pdfBusy}
        >
          {pdfBusy ? <Loader2 size={13} className="animate-spin" /> : <FileText size={13} />}
          PDF
        </Button>

        <Button
          variant="outline" size="sm"
          className="h-8 gap-1.5 text-xs"
          onClick={() => downloadExcel(config)}
        >
          <FileSpreadsheet size={13} /> Excel
        </Button>

        <Button
          variant="outline" size="sm"
          className="h-8 gap-1.5 text-xs"
          onClick={() => downloadWord(config)}
        >
          <FileType size={13} /> Word
        </Button>

        <Button
          variant="outline" size="sm"
          className="h-8 gap-1.5 text-xs"
          onClick={openEmail}
        >
          <Mail size={13} /> Email
        </Button>
      </div>

      {/* ── Email Dialog ── */}
      <Dialog open={emailOpen} onOpenChange={setEmailOpen}>
        <DialogContent className="max-w-sm">
          <DialogHeader>
            <DialogTitle className="text-base flex items-center gap-2">
              <Mail size={15} className="text-primary" /> Send Summary by Email
            </DialogTitle>
          </DialogHeader>

          <div className="space-y-3 py-1">
            <div>
              <Label htmlFor="export-email-to" className="text-xs font-semibold">
                Recipient Email
              </Label>
              <Input
                id="export-email-to"
                type="email"
                placeholder="e.g. owner@clinic.com"
                value={emailTo}
                onChange={(e) => setEmailTo(e.target.value)}
                className="mt-1.5 h-9"
                onKeyDown={(e) => { if (e.key === "Enter") void handleSend(); }}
                autoFocus
              />
            </div>

            <div className="rounded-lg bg-gray-50 dark:bg-muted/20 p-3">
              <p className="text-xs font-semibold text-gray-700 dark:text-gray-300 mb-0.5">Subject:</p>
              <p className="text-xs text-gray-600 dark:text-gray-400 truncate">
                {config.title} — {config.subtitle}
              </p>
            </div>

            {result && (
              <div
                className={`flex items-center gap-2 rounded-lg p-2.5 text-xs font-semibold
                  ${result.ok
                    ? "bg-green-50 dark:bg-green-950/20 text-green-700 dark:text-green-400"
                    : "bg-red-50 dark:bg-red-950/20 text-red-600 dark:text-red-400"
                  }`}
              >
                {result.ok ? <CheckCircle2 size={13} /> : <AlertCircle size={13} />}
                {result.ok ? "Email sent successfully!" : (result.error ?? "Send failed.")}
              </div>
            )}
          </div>

          <DialogFooter className="gap-2 pt-1">
            <DialogClose asChild>
              <Button variant="outline" size="sm">Cancel</Button>
            </DialogClose>
            <Button
              size="sm"
              onClick={handleSend}
              disabled={sending || !emailTo.trim() || result?.ok === true}
            >
              {sending
                ? <><Loader2 size={13} className="animate-spin mr-1" /> Sending…</>
                : "Send"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
